#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
#
#FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
#WORKDIR /app
#EXPOSE 80
#EXPOSE 443
#
#FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
#WORKDIR /src
#COPY ["ArkThor.API.csproj", "ArkThor.API/"]
#RUN dotnet restore "ArkThor.API/ArkThor.API.csproj"
#COPY . .
#WORKDIR "/src/ArkThor.API"
#RUN dotnet build "ArkThor.API.csproj" -c Release -o /app/build
#
#FROM build AS publish
#RUN dotnet publish "ArkThor.API.csproj" -c Release -o /app/publish /p:UseAppHost=false
#
#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app/publish .
#ENTRYPOINT ["dotnet", "ArkThor.API.dll"]

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY published/arkthorapi/ ./
ENTRYPOINT ["dotnet", "ArkThor.API.dll"]