version: '3.9'

services:
  ui:
    image: arkthor-ui
    container_name: arkthorui
    ports:
      - "24297:80"    
    networks:
      - nwarkthor
  api:
    image: arkthor-api
    container_name: arkthorapi
    ports:
      - "33900:80"
    volumes:
      - type: bind
        source: ${PWD}/UploadedFiles
        target: /app/UploadedFiles
      - type: bind
        source: ${PWD}/ArkThorDatabase
        target: /app/ArkThorDatabase
    networks:
      - nwarkthor

networks:
  nwarkthor:
    name: nwarkthor
