version: '3.9'

services:

  api:
    image: arkthor-api
    container_name: arkthorapi
    ports:
      - "33900:80"
    volumes:
      - type: bind
        source: ./UploadedFiles
        target: /app/UploadedFiles
      - type: bind
        source: ./ArkThorDatabase
        target: /app/ArkThorDatabase
    networks:
      - nwarkthor
  
  ui:
    image: arkthor-ui
    container_name: arkthorui
    depends_on:
      - api
    ports:
      - "24297:80"    
    networks:
      - nwarkthor 
  core:
    image: arkthor-core
    container_name: arkthorcore
    depends_on:
      - api
      - rabbitmq
    volumes:
      - type: bind
        source: ./UploadedFiles
        target: /app/UploadedFiles
    networks:
      - nwarkthor
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    depends_on:
      - api
    ports:
      - "15672:15672"
    networks:
      - nwarkthor
networks:
  nwarkthor:
    name: nwarkthor
