version: '3.9'

services:

  arkthorui:
    image: arkthor/arkthor-ui:latest
    depends_on:
      - arkthorapi
    ports:
      - "24297:80"    
    networks:
      - nwarkthor

  arkthorapi:
    image: arkthor/arkthor-api:latest
    depends_on:
      - rabbitmq
    ports:
      - "33900:80"
    volumes:
      - type: bind
        source: ./UploadedFiles
        target: /app/UploadedFiles
      - type: bind
        source: ./ArkThorDatabase
        target: /app/ArkThorDatabase
    networks:
      - nwarkthor

  arkthorcore:
    image: arkthor/arkthor-core:latest
    depends_on:
      - arkthorapi
    volumes:
      - type: bind
        source: ./UploadedFiles
        target: /app/UploadedFiles
    networks:
      - nwarkthor  
 
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - nwarkthor
networks:
  nwarkthor:
    name: nwarkthor
