version: '3.9'

services:
  ui:
    image: arkthor-ui
    container_name: arkthorui
    depends_on:
      - api
    ports:
      - "24297:80"    
    networks:
      - nwarkthor
  api:
    image: arkthor-api
    container_name: arkthorapi
    ports:
      - "33900:80"
    volumes:
      - type: bind
        source: ./UploadedFiles
        target: /app/UploadedFiles
      - type: bind
        source: ./ArkThorDatabase
        target: /app/ArkThorDatabase
    networks:
      - nwarkthor
  core:
    image: arkthor-core
    container_name: arkthorcore
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./UploadedFiles
        target: /app/UploadedFiles
    networks:
      - nwarkthor
   
networks:
  nwarkthor:
    name: nwarkthor
