version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./certs/live/arkthor.com:/etc/nginx/ssl
    depends_on:
      - arkthorui
      - arkthorapi
      - rabbitmq
      - arkthorcore
    networks:
      - nwarkthor
    logging:
        options:
            max-size: "10m"
            max-file: "3"

  arkthorui:
    image: arkthor/arkthor-ui:livehosting
    container_name: arkthorui
    restart: "always"
    depends_on:
      - arkthorapi
    networks:
      - nwarkthor
  
  arkthorapi:
    image: arkthor/arkthor-api:livehostingV2
    container_name: arkthorapi
    restart: "always"
    depends_on:
      - rabbitmq
    volumes:
      - "AnalysesFiles:/app/UploadedFiles"
      - "Database:/app/ArkThorDatabase"
    
    networks:
      - nwarkthor
  
  arkthorcore:
    image: arkthor/arkthor-core:latest
    restart: "always"
    deploy:
      replicas: 1 
    depends_on:
      - arkthorapi
      - rabbitmq
    volumes:
      - "AnalysesFiles:/app/UploadedFiles"      
    networks:
      - nwarkthor
      
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: "always"
    container_name: rabbitmq
    expose:
      - "15672"
    networks:
      - nwarkthor
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: "no"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jawed.ace@gmail.com --agree-tos --no-eff-email -d arkthor.com -d www.arkthor.com
    networks:
      - nwarkthor
    depends_on:
      - nginx

volumes:
  AnalysesFiles:
  Database: 
networks:
  nwarkthor:
    name: nwarkthor
