#FROM python:3.9-slim-buster
FROM python:alpine3.17
#FROM python:3.7-windowsservercore-1809
WORKDIR /app
COPY Core/requirements.txt requirements.txt
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY Core/. .

#RUN ["python", "./ip2asn.py"]

CMD ["python", "./pscap.py"]
